name: s-pdf
include:
  - ../common/networks.yaml
services:
  s-pdf:
    image: frooodle/s-pdf:2.14.3@sha256:3b3670fce70b396ec56ba380a3cc7858e0abf83fe13f31c88f7737847763a396
    networks:
      - proxy
    labels:
      traefik.http.routers.s-pdf.rule: Host(`s-pdf.${BASE_DOMAIN}`)
      traefik.http.services.s-pdf.loadbalancer.server.port: 8080
      traefik.http.routers.s-pdf.tls: true
      traefik.http.routers.s-pdf.middlewares: authelia@docker
      traefik.enable: true
    restart: unless-stopped
