name: s-pdf
include:
  - ../common/networks.yaml
services:
  s-pdf:
    image: frooodle/s-pdf:1.6.0@sha256:1f73a8f898fe269cbbccea3be577064dd87fc4334de349fcc5b1afa1bcebf240
    networks:
      - proxy
    labels:
      traefik.http.routers.s-pdf.rule: Host(`s-pdf.${BASE_DOMAIN}`)
      traefik.http.services.s-pdf.loadbalancer.server.port: 8080
      traefik.http.routers.s-pdf.tls: true
      traefik.http.routers.s-pdf.middlewares: authelia@docker
      traefik.enable: true
    restart: unless-stopped
