<<: !include
    - repositories/constants.yaml
    - constants/docker.yaml
    - encryption/docker-secret.yaml
    - name-formats/docker.yaml
    - retention/7d.yaml

constants:
    volume_name: adguard-conf

source_directories:
    !include sources/docker-volume.yaml

repositories:
    !include repositories/all.yaml
