<<: !include
    - includes/common.yaml

constants:
    archive_name: adguard
    borgbase_repo_id: ${BORGBASE_ADGUARD_REPO_ID}
    volume_name: adguard-conf

source_directories:
    !include sources/docker-volume.yaml
