<<: !include
    - constants/docker.yaml
    - constants/repositories.yaml.yaml
    - encryption/docker-secret.yaml
    - hooks/repositories-all.yaml
    - name-formats/docker.yaml
    - retention/7d.yaml
    - repositories/all.yaml

constants:
    archive_name: adguard
    borgbase_repo_id: mv307xu0
    volume_name: adguard-conf

source_directories:
    !include sources/docker-volume.yaml
