<<: !include
    - includes/common.yaml

constants:
    archive_name: authelia
    borgbase_repo_id: ${BORGBASE_AUTHELIA_REPO_ID}
    pg_name: authelia
    pg_host: authelia-database
    pg_user: authelia
    pg_pass: ${AUTHELIA_POSTGRES_PASSWORD}
    volume_name: authelia-database

postgresql_databases:
    !include sources/pg-database.yaml
