<<: !include
    - includes/common.yaml
    - hooks/nextcloud-maintenance.yaml

constants:
    archive_name: nextcloud
    borgbase_repo_id: ${BORGBASE_NEXTCLOUD_REPO_ID}
    mariadb_name: nextcloud
    mariadb_host: nextcloud-database
    mariadb_user: nextcloud
    mariadb_pass: ${NEXTCLOUD_MARIADB_PASSWORD}

source_directories:
    - "{docker_volumes_path}/nextcloud-data/config"
    - "{docker_volumes_path}/nextcloud-data/data"
    - "{docker_volumes_path}/nextcloud-data/themes"

mariadb_databases:
    !include sources/mariadb-database.yaml
