<<: !include
    - repositories/constants.yaml
    - constants/docker.yaml
    - encryption/docker-secret.yaml
    - hooks/nextcloud-maintenance.yaml
    - hooks/repositories-all.yaml
    - name-formats/docker.yaml
    - retention/7d.yaml
    - repositories/all.yaml

constants:
    archive_name: nextcloud
    borgbase_repo_id: lw5dp5e7
    mariadb_name: nextcloud
    mariadb_host: nextcloud-database
    mariadb_user: nextcloud
    mariadb_pass: ${NEXTCLOUD_MARIADB_PASSWORD}

source_directories:
    - "{docker_volumes_path}/nextcloud-data/config"
    - "{docker_volumes_path}/nextcloud-data/data"
    - "{docker_volumes_path}/nextcloud-data/themes"

mariadb_databases:
    !include sources/mariadb-database.yaml
