<<: !include
    - repositories/constants.yaml
    - constants/docker.yaml
    - encryption/docker-secret.yaml
    - hooks/repositories-all.yaml
    - name-formats/docker-custom.yaml
    - retention/7d.yaml
    - repositories/all.yaml

constants:
    archive_name: plex
    borgbase_repo_id: gx8b14fp
    volume_name: plex-config

source_directories:
    !include sources/docker-volume.yaml

exclude_patterns:
    - '{docker_volumes_path}/{volume_name}/Library/Application Support/Plex Media Server/Cache'
