<<: !include
    - includes/common.yaml

constants:
    archive_name: plex
    borgbase_repo_id: gx8b14fp
    volume_name: plex-config

source_directories:
    !include sources/docker-volume.yaml

exclude_patterns:
    - '{docker_volumes_path}/{volume_name}/Library/Application Support/Plex Media Server/Cache'
