<<: !include
    - includes/common.yaml

constants:
    archive_name: plex
    borgbase_repo_id: ${BORGBASE_PLEX_REPO_ID}
    volume_name: plex-config

source_directories:
    !include sources/docker-volume.yaml

exclude_patterns:
    - '{docker_volumes_path}/{volume_name}/Library/Application Support/Plex Media Server/Cache'
