<<: !include
    - constants/repositories.yaml
    - encryption/docker-secret.yaml
    - hooks/repositories-all.yaml
    - name-formats/docker.yaml
    - retention/7d.yaml
    - repositories/all.yaml

constants:
    archive_name: secrets
    borgbase_repo_id: ${BORGBASE_SECRETS_REPO_ID}

source_directories:
    - /run/secrets
