<<: !include
    - includes/common.yaml
    - excludes/sqlite-files.yaml
    - hooks/vaultwarden-maintenance.yaml

constants:
    archive_name: vaultwarden
    borgbase_repo_id: gb7fgee1
    sqlite_name: vaultwarden
    sqlite_path: db.sqlite3
    volume_name: vaultwarden-data

source_directories:
    !include sources/docker-volume.yaml

sqlite_databases:
    !include sources/sqlite-database.yaml

exclude_patterns:
    - '{docker_volumes_path}/{volume_name}/icon_cache'
