name: my-whole-server
services:
# ============================================================================ #
# ================================= BORGMATIC ================================ #
# ============================================================================ #
  borgmatic:
    image: ghcr.io/borgmatic-collective/borgmatic:2.1.7@sha256:6d039f98e58a58cea287007608c3d5993ce65f8e248ff91cd3de4246c648c123
    environment:
      BORG_PASSPHRASE_FILE: /run/secrets/BORGMATIC_ENCRYPTION_PASSPHRASE
      CRON: "0 2 * * *"
      TZ: Europe/Paris
      NEXTCLOUD_CONTAINER_NAME: my-whole-server-nextcloud-app-1
      VAULTWARDEN_CONTAINER_NAME: my-whole-server-vaultwarden-1
    env_file:
      - ./borgmatic/envs/databases.sops.env
      - ./borgmatic/envs/borgbase.sops.env
    volumes:
      - borg-config:/root/.config/borg
      - borg-cache:/root/.cache/borg
      - ./borgmatic/config:/etc/borgmatic.d
      - ./borgmatic/scripts:/scripts:ro
      - adguard-conf:/volumes/adguard-conf
      - nextcloud-data:/volumes/nextcloud-data
      - plex-config:/volumes/plex-config
      - vaultwarden-data:/volumes/vaultwarden-data
      - /backup/local/borg/docker:/backup/local
      - /var/run/docker.sock:/var/run/docker.sock
      - node-textfile-collector:/var/lib/node_exporter/textfile_collector
    networks:
      - backup
    secrets:
      - AUTHELIA_JWT_SECRET
      - AUTHELIA_SESSION_SECRET
      - AUTHELIA_STORAGE_ENCRYPTION_KEY
      - AUTHELIA_STORAGE_PASSWORD
      - BORGMATIC_ENCRYPTION_PASSPHRASE
      - LDAP_ADMIN_PASSWORD
      - NEXTCLOUD_STORAGE_PASSWORD
      - SMTP_PASSWORD
      - VAULTWARDEN_ADMIN_TOKEN
      - source: BORGMATIC_SSH_PRIVATE_KEY
        target: /root/.ssh/id_rsa
        mode: 0400
      - source: BORGMATIC_SSH_KNOWN_HOSTS
        target: /root/.ssh/known_hosts
        mode: 0400
    healthcheck:
      disable: true
    restart: unless-stopped

volumes:
  adguard-conf:
  borg-cache:
  borg-config:
  nextcloud-data:
  node-textfile-collector:
  plex-config:
  vaultwarden-data:

networks:
  backup:
  proxy:
    external: true
    name: proxy

secrets:
  AUTHELIA_JWT_SECRET:
    file: ${SECRETS_DIR:-./}authelia/secrets/JWT_SECRET
  AUTHELIA_SESSION_SECRET:
    file: ${SECRETS_DIR:-./}authelia/secrets/SESSION_SECRET
  AUTHELIA_STORAGE_PASSWORD:
    file: ${SECRETS_DIR:-./}authelia/secrets/STORAGE_PASSWORD
  AUTHELIA_STORAGE_ENCRYPTION_KEY:
    file: ${SECRETS_DIR:-./}authelia/secrets/STORAGE_ENCRYPTION_KEY
  BORGMATIC_ENCRYPTION_PASSPHRASE:
    file: ${SECRETS_DIR:-./}borgmatic/secrets/ENCRYPTION_PASSPHRASE
  LDAP_ADMIN_PASSWORD:
    file: ${SECRETS_DIR:-./}ldap/secrets/ADMIN_PASSWORD
  NEXTCLOUD_STORAGE_PASSWORD:
    file: ${SECRETS_DIR:-./}nextcloud/secrets/STORAGE_PASSWORD
  SMTP_PASSWORD:
    file: ${SECRETS_DIR:-./}secrets/SMTP_PASSWORD
  VAULTWARDEN_ADMIN_TOKEN:
    file: ${SECRETS_DIR:-./}vaultwarden/secrets/ADMIN_TOKEN
  BORGMATIC_SSH_PRIVATE_KEY:
    file: ${SECRETS_DIR:-./}borgmatic/secrets/SSH_PRIVATE_KEY
  BORGMATIC_SSH_KNOWN_HOSTS:
    file: ${SECRETS_DIR:-./}borgmatic/secrets/SSH_KNOWN_HOSTS
