before_backup:
  - sh /scripts/nextcloud-maintenance.sh on

after_backup:
  - sh /scripts/nextcloud-maintenance.sh off

before_extract:
  - sh /scripts/nextcloud-maintenance.sh on

after_extract:
  - sh /scripts/nextcloud-maintenance.sh off
  - sh /scripts/nextcloud-data-fingerprint.sh
