FROM prom/prometheus:v3.15.0@sha256:efd719c99d83b060d9daefdcf00360461adf279f45ef5391f8d111892118753e

USER root
COPY prometheus.yml /etc/prometheus/prometheus.template.yml
COPY entrypoint.sh /entrypoint.sh
RUN chmod 0755 /entrypoint.sh
USER nobody

ENTRYPOINT ["/entrypoint.sh"]
