global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: "transmission"
  static_configs:
    - targets: ["transmission-exporter:19091"]
- job_name: "node"
  static_configs:
    - targets: ["node-exporter:9100"]
- job_name: aggregated-trace-metrics
  static_configs:
    - targets: ['otel-collector:8889']
