name: da-many
include:
  - ../common/networks.yaml
services:
  database:
    image: postgres:18-alpine@sha256:77f585114c32fbca283dc835b0596f4e52b51b4c6662d7810b2f4084f60a1873
    environment:
      POSTGRES_DB: da-many
      POSTGRES_USER: da-many
      POSTGRES_PASSWORD: ${DA_MANY_DATABASE_PASSWORD}
    volumes:
      - database:/var/lib/postgresql
    networks:
      backend: {}
      backup:
        aliases:
          - da-many-database
    restart: unless-stopped

  da-many-api:
    image: ghcr.io/valfur03/da-many-api:branch-main
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://da-many:${DA_MANY_DATABASE_PASSWORD}@database:5432/da-many
      BETTER_AUTH_URL: https://money.${BASE_DOMAIN}
      WEB_ORIGIN: https://money.${BASE_DOMAIN}
      BETTER_AUTH_SECRET: ${DA_MANY_AUTH_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: 587
      SMTP_USER: ${SMTP_USERNAME}
      SMTP_PASS: ${SMTP_PASSWORD}
      SMTP_FROM: ${DA_MANY_SYSTEM_EMAIL}
    networks:
      - backend
      - proxy
    labels:
      traefik.http.middlewares.da-many-stripapi.stripprefix.prefixes: /api
      traefik.http.routers.da-many-api.rule: Host(`money.${BASE_DOMAIN}`) && PathPrefix(`/api`)
      traefik.http.routers.da-many-api.middlewares: da-many-stripapi
      traefik.http.routers.da-many-api.service: da-many-api
      traefik.http.routers.da-many-api.tls: true
      traefik.http.services.da-many-api.loadbalancer.server.port: 3000
      traefik.enable: true
    restart: unless-stopped

  da-many-web:
    image: ghcr.io/valfur03/da-many-web:branch-main
    environment:
      API_URL: https://money.${BASE_DOMAIN}/api
    networks:
      - proxy
    labels:
      traefik.http.routers.da-many-web.rule: Host(`money.${BASE_DOMAIN}`)
      traefik.http.routers.da-many-web.tls: true
      traefik.http.services.da-many-web.loadbalancer.server.port: 80
      traefik.enable: true
    restart: unless-stopped

volumes:
  database:

networks:
  backend:
