name: http
services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy@sha256:1f3a6f303320723d199d2316a3e82b2e2685d86c275d5e3deeaf182573b47476
    environment:
      CONTAINERS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket
    restart: unless-stopped

  traefik:
    image: traefik:v3.7.1@sha256:6b9cbca6fac42ab0075f5437d8dc1685cfd188626d8d515839ea94f8b6271c42
    depends_on:
      - socket-proxy
    ports:
      - 80:80
      - 443:443
    environment:
      TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL: ${SYSTEM_EMAIL:?see .env.example}
      BUNNY_API_KEY_FILE: /run/secrets/bunny_api_key
      TRAEFIK_ENTRYPOINTS_HTTPS_HTTP_TLS: "true"
      TRAEFIK_ENTRYPOINTS_HTTPS_HTTP_TLS_CERTRESOLVER: letsencrypt
      TRAEFIK_ENTRYPOINTS_HTTPS_HTTP_TLS_DOMAINS_0_MAIN: ${BASE_DOMAIN:?see .env.example}
      TRAEFIK_ENTRYPOINTS_HTTPS_HTTP_TLS_DOMAINS_0_SANS: "*.${BASE_DOMAIN},*.collector.traces.${BASE_DOMAIN}"
    volumes:
      - acme:/etc/traefik/acme
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - proxy
      - socket
      - metrics
    extra_hosts:
      - host.docker.internal:172.17.0.1
    secrets:
      - bunny_api_key
    labels:
      traefik.http.routers.traefik.rule: Host(`proxy.${BASE_DOMAIN}`)
      traefik.http.routers.traefik.tls: true
      traefik.http.routers.traefik.middlewares: authelia@docker
      traefik.http.routers.traefik.service: api@internal
      traefik.http.services.traefik.loadbalancer.server.port: 8080
      traefik.enable: true
    restart: unless-stopped

networks:
  proxy:
    name: proxy
    ipam:
      driver: default
      config:
        - subnet: 172.47.0.0/16
  socket:
    internal: true
  metrics:
    external: true

volumes:
  acme:

secrets:
  bunny_api_key:
    file: ./secrets/bunny_api_key
