name: weekly-money
include:
  - ../common/networks.yaml
services:
  database:
    image: postgres:16.1-alpine3.17@sha256:7e26cdee39d74f2f8cd527dc3bf8e675d008a2120fab3aded96d546ff12c9519
    environment:
      POSTGRES_DB: weekly-money
      POSTGRES_USER: weekly-money
      POSTGRES_PASSWORD: ${WEEKLY_MONEY_DATABASE_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped

  weekly-money:
    image: ghcr.io/valfur03/weekly-money:main
    depends_on:
      - database
    environment:
      NOTION_ACCESS_TOKEN: ${NOTION_ACCESS_TOKEN}
      NOTION_PRODUCTS_DATASOURCE_ID: ${NOTION_PRODUCTS_DATASOURCE_ID}
      NOTION_PORTFOLIO_DATASOURCE_ID: ${NOTION_PORTFOLIO_DATASOURCE_ID}
      NOTION_PORTFOLIO_ACCOUNT_ID: ${NOTION_PORTFOLIO_ACCOUNT_ID}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_USER_ID: ${DISCORD_USER_ID}
      ALPHA_VANTAGE_API_KEY: ${ALPHA_VANTAGE_API_KEY}
      DATABASE_HOST: database
      DATABASE_USER: weekly-money
      DATABASE_NAME: weekly-money
      DATABASE_PASSWORD: ${WEEKLY_MONEY_DATABASE_PASSWORD}
      BASE_DOMAIN: weekly-money.${BASE_DOMAIN}
      LOG_LEVEL: debug
    networks:
      - proxy
      - backend
    labels:
      traefik.http.routers.weekly-money.rule: Host(`weekly-money.${BASE_DOMAIN}`)
      traefik.http.routers.weekly-money.tls: true
      traefik.http.services.weekly-money.loadbalancer.server.port: 3000
      traefik.enable: true
    restart: unless-stopped

volumes:
  database:

networks:
  backend:
