authentication_backend:
  ldap:
    url: ldap://ldap
    users_filter: (&({username_attribute}={input})(objectClass=iNetOrgPerson))
    username_attribute: cn
    display_name_attribute: sn
    groups_filter: (&(uniquemember={dn})(objectclass=groupOfUniqueNames))
    group_name_attribute: cn
storage:
  postgres:
    host: authelia-database
    database: authelia
    username: authelia
session:
  redis:
    host: authelia-redis
    port: 6379
notifier:
  smtp:
    port: 465
    subject: "[Valfur Authelia] {title}"
    tls:
      skip_verify: false
      minimum_version: TLS1.2
