name: frps
include:
  - ../common/networks.yaml
services:
  frps:
    image: snowdreamtech/frps:alpine@sha256:9266755999eea2ce3f4c0f41eeaf62b3955b2938582fdeaa6fcd8513a7be10b0
    environment:
      FRP_AUTH_TOKEN: ${FRP_AUTH_TOKEN}
    volumes:
      - ./frps.toml:/etc/frp/frps.toml:ro
    ports:
      - 7000:7000
    networks:
      - proxy
      - metrics
    labels:
      traefik.http.routers.frps.rule: HostRegexp(`^.+-tunnel\.${BASE_DOMAIN}$`)
      traefik.http.routers.frps.tls: true
      traefik.http.services.frps.loadbalancer.server.port: 8080
      traefik.enable: true
    restart: unless-stopped
